# Generated by Django 5.1.2 on 2024-10-21 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_statusmessage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmessage',
            name='image',
        ),
    ]
